apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-management-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-management-database
  template:
    metadata:
      labels:
        app: tenant-management-database
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "nilesh@root"
            - name: MYSQL_DATABASE
              value: "tenant_management"
            - name: MYSQL_USER
              value: "nilesh"
            - name: MYSQL_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: tenant-mysql-pvc
