apiVersion: v1
kind: Service
metadata:
  name: tenant-management-database-service
spec:
  type: NodePort
  selector:
    app: tenant-management-database
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32206