apiVersion: v1
kind: Service
metadata:
  name: tenant-management-service
spec:
  type: NodePort
  selector:
    app: tenant-management
  ports:
    - name: tenant-management
      protocol: TCP
      port: 3007
      targetPort: 3007
      nodePort: 32205
