apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: property-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: property-management-database-service
spec:
  selector:
    app: property-management-database
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-management-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-management-database
  template:
    metadata:
      labels:
        app: property-management-database
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "nilesh@root"
            - name: MYSQL_DATABASE
              value: "property_management"
            - name: MYSQL_USER
              value: "nilesh"
            - name: MYSQL_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: property-mysql-pvc
