apiVersion: v1
kind: Service
metadata:
  name: property-management-srv
spec:
  type: NodePort
  selector:
    app: property-management
  ports:
    - name: property-management
      protocol: TCP
      port: 3006
      targetPort: 3006
      nodePort: 32105